### ISSUE TITLE
Buggy collision upon going left, or up.

### ISSUE THREAD

**Issue by ghost** [Tjstretchalot/SharpMath2#2]
Hey there! 

It's me again,

There seems to be an issue when colliding with numerous objects going  left, and up. I've re-written my code a few times, even tried it without the quad tree but the problem persists. I'm unsure at this point where the problem is so I'm hoping you could shed some light on it, as I'm not very familiar with your code.

![da6da46c462dd04fd8cddc4a2c13f678](https://user-images.githubusercontent.com/20602971/32574357-478160f2-c4d1-11e7-8d8f-6990a31a3b0c.gif)

I first thought it had to do with the quad tree (as the tree wasn't dynamically expanding), but it then turns out that by just pushing one block at a time there was no issue. This issue does not exist for moving to the right or the bottom so I'm assuming it's a form of rounding error.

I've included a copy of my source in case you need it. 
[Engine.zip](https://github.com/Tjstretchalot/SharpMath2/files/1455419/Engine.zip)

**Update**: I've adjusted the following zip to exclude quad trees, and strangely enough - now it does somewhat work better, but it seems to just pick and choose which ones to push away and which ones not to. Is the pushing away suppose to be happening? I know it happens because I also check collisions for the non player-boxes, but still. It seems to pick and choose.

![80bec15aacfe79e95fa051a427cef348](https://user-images.githubusercontent.com/20602971/32575610-cd7c87d8-c4d4-11e7-8070-f3d83cd19cc6.gif)

I got a feeling it's me not understanding the library that is the issue.
[Engine No Trees.zip](https://github.com/Tjstretchalot/SharpMath2/files/1455481/Engine.No.Trees.zip)

**Comment by Tjstretchalot** [comment]
Hmm, my first guess is it's because SAT doesn't work very well if you have a lot of collisions, it's meant for situations where collisions are unlikely to cause other collisions. After running your code you linked with the tree it worked on my computer unless you went very quickly.

Remember with SAT theres no concept of velocity, so if you skip over to the right side of something SAT is going to push the other object left, even if in the previous frame the moving object was on the left.

Easiest fix for this would be to limit movement speed or, if the movement is fast to split the collision into multiple chunks (ie. repeat 5 small movements rather than do 1 large movement)

Can you replicate this bug at small speeds?

**Comment by ghost** [comment]
> Remember with SAT theres no concept of velocity

Right, I currently am not using velocity. I'm directly setting the position (well, lerping the position of the player to the mouse position.)

In the last .zip I send you without the quad trees (so we can disqualify that being relevant to the issue) I am moving the player to the mouse with a speed roughly 2 pixels per update (60 updates per second.)

1. Move by ~2 pixels.
2. Resolve collisions (this one is also for every other object.)

I don't think that's unreasonably fast, or should be unreasonably fast enough to cause any issues.

**Comment by Tjstretchalot** [comment]
Hmmm could you set up a thing that doesn't require mouse movement that shows the bug? Like just have him start somewhere and hardcode the velocity so it's easier for me to see the bug

**Comment by ghost** [comment]
Sure, no problem!

**Comment by ghost** [comment]
Apparently by not using the mouse it seems to not even move the other boxes around. I suppose it's resolved then?

**Comment by Tjstretchalot** [comment]
If it's not moving the other boxes you might have the collision order backwards. One box has to move to resolve the collision, but it'll look like nothing is moving if you have it resolving the collision by moving the moving guy (it'll put him back to where he used to be). That would also explain the inconsistent behavior in your gif

**Comment by ghost** [comment]
Right, I suppose in the original gif it resolved other boxes instead of the one that actually moved - pushing them away instead of the "player"/mouse box.

**Comment by ghost** [comment]
Okay great, I can finally add ray casting then to make sure it won't teleport over the boxes with velocity to include the "small step" that you advised. Seems there's a word for that kind of behavior and it's called tunneling.

**Comment by ghost** [comment]
Sorry about the inconvenience, seems like it was a problem of mine after all.

**Comment by Tjstretchalot** [comment]
So swapping the order fixed it? And it's no problem at all :)

**Comment by ghost** [comment]
I think swapping was part of the problem - I think the entire problem was two subsets:

1. Potentially moving too fast over the blocks making the collisions only valid going up and left (as opposed to thinking they were the problem.)
2. Resolving in a different order every time creating a "push away" behavior when in reality it's the player that had to "push away" from the other blocks.

**Comment by ghost** [comment]
Interesting nonetheless! Humility at its finest today as I once again realize programming can drive you insane and will make you turn against other people.
