### ISSUE TITLE
Circle2 IntersectMTV not working correctly

### ISSUE THREAD

**Issue by EnemyArea** [Tjstretchalot/SharpMath2#5]
Hello guys,

I dont know whether someone will read this, but could you please fix the IntersectMTV-method of the Circle2 class? It does not give the right results if the circles overlap. The Intersects method is broken too, if there are two circles with different radii.

Thank you :)

---Edit: Circle and Polygon is broken too :(---
Edit2: I dont have see that there a two methods.. Circle-Polygon and Polygon-Circle :(

The line-class has a bug for calculating the Horizontal and Vertical

That fixed it... buts still broken on the resolving of the collisions
var k = Math.Abs(this.End.Y - this.Start.Y) / Math.Abs(this.End.X - this.Start.X);
this.Horizontal = k == 0;
this.Vertical = float.IsInfinity(k);

**Comment by Tjstretchalot** [comment]
I'm about to need circles in my project so now is a good a time as any for me to look into it. I'll try to have it fixed in the next 24 hours

**Comment by Tjstretchalot** [comment]
https://github.com/Tjstretchalot/SharpMath2/commit/a6ad02ae7be5a0687f2eba50b1f796c738a446e4 fixes this

**Comment by EnemyArea** [comment]
Thank you very much, works like a charm ;D
I used your code here: https://github.com/EnemyArea/CollisionHandling/tree/develop
Feel free to use it too. I build a little testbed (indev) and try to visualiate the shapes.

Have you fixed the bug in the Line class too?

**Comment by Tjstretchalot** [comment]
Ahh sorry I read to fast and missed the bug for the line - I'll look into this

**Comment by Tjstretchalot** [comment]
Fixed with https://github.com/Tjstretchalot/SharpMath2/commit/e2efa787e3ad6a2c6c9d86d7eb2ae795c614232e
