### ISSUE TITLE
Polygon2.Contains doesn't work properly

### ISSUE THREAD

**Issue by Slaktus** [Tjstretchalot/SharpMath2#6]
When a long rectangle is checked against a small circle along a diagonal axis, the Polygon2.Contains test misreports overlaps. See pictures: [https://imgur.com/a/tuuV5Ph](https://imgur.com/a/tuuV5Ph)

**Comment by Tjstretchalot** [comment]
Thank you for the report! I'm looking into this now. I just want to verify you tried this on the latest version

**Comment by Tjstretchalot** [comment]
It would also be very helpful if you could Console.WriteLine the vertices for the rectangle, the rectangles position, the circles position, and the circle radius when the incorrect result is returned

**Comment by Tjstretchalot** [comment]
I've found a more resilient approach for polygon intersection that should resolve this issue, coding it up now

**Comment by Tjstretchalot** [comment]
I believe this is fixed with https://github.com/Tjstretchalot/SharpMath2/commit/a48eb507daee280d39f884e550fc0c362040f6d3
